### ISSUE TITLE
SQLAlchemyError error processing event caused by Emojis

### ISSUE THREAD

**Issue by craigmcgowan** [custom-components/youtube#38]
**Version of the custom_component**
0.7.0

**Describe the bug**
When people post to Youtube and use emojis in their titles, it causes an issue when this component tries to write to the recorder. Normally I get this with Quindor who likes to use emojis in titles of his videos, but this week its Smart Home Solver too. You can see the Emoji string value seems to be causing an issue. I guess it needs to be sanitized in someway but im unsure how.

![image](https://user-images.githubusercontent.com/40320690/119257859-1cb98500-bbbf-11eb-905c-fa0d3647830b.png)

**log**
```
2021-05-23 11:58:30 ERROR (Recorder) [homeassistant.components.recorder] SQLAlchemyError error processing event <Event time_changed[L]: now=2021-05-23T11:58:27.000460+01:00>: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\xAC' for column `homeassistant`.`states`.`state` at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.smart_home_solver', 'I just spent thousands on Lutron…😬', '{"url": "https://www.youtube.com/watch?v=GBWtmJPCyGc", "published": "2021-05-22T16:49:21+00:00", "stars": "786", "views": "17005", "stream": false, " ... (137 characters truncated) ... z_B4ajnU_M1EbaQ", "friendly_name": "Smart Home Solver", "icon": "mdi:youtube", "entity_picture": "https://i4.ytimg.com/vi/GBWtmJPCyGc/hqdefault.jpg"}', 49262423, datetime.datetime(2021, 5, 23, 10, 56, 56, 643312, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 5, 23, 10, 58, 26, 881512, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 5, 23, 10, 58, 26, 881512, tzinfo=datetime.timezone.utc), None)]
(Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 534, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 627, in _process_one_event
    self._commit_event_session_or_retry()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 690, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 716, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 824, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 598, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x98\\xAC' for column `homeassistant`.`states`.`state` at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.smart_home_solver', 'I just spent thousands on Lutron…😬', '{"url": "https://www.youtube.com/watch?v=GBWtmJPCyGc", "published": "2021-05-22T16:49:21+00:00", "stars": "786", "views": "17005", "stream": false, " ... (137 characters truncated) ... z_B4ajnU_M1EbaQ", "friendly_name": "Smart Home Solver", "icon": "mdi:youtube", "entity_picture": "https://i4.ytimg.com/vi/GBWtmJPCyGc/hqdefault.jpg"}', 49262423, datetime.datetime(2021, 5, 23, 10, 56, 56, 643312, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 5, 23, 10, 58, 26, 881512, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 5, 23, 10, 58, 26, 881512, tzinfo=datetime.timezone.utc), None)]
(Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)
```

**Comment by ludeeus** [comment]
I'm guessing your recorder is not properly set up.
<https://github.com/home-assistant/core/issues/43082>

This is anyway not something each integration can or should control, this "issue" is not limited to this integration, you will have that everywhere.
If the linked issue does not help you, try the HA discord.
